data_url: PCB_DATASET_COCO
train_url: model
model_name: s
weights: Yolov5_for_PyTorch/yolov5s.pt
cfg: Yolov5_for_PyTorch/models/yolov5s.yaml
data: Yolov5_for_PyTorch/data/coco.yaml
hyp: Yolov5_for_PyTorch/data/hyps/hyp.scratch.yaml
epochs: 50
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: Yolov5_for_PyTorch/runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
noscale: false
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
native_amp: false
FP32: false
save_dir: Yolov5_for_PyTorch/runs/train/exp4
